### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dabellator**
Hi James,

Interesting assignment, there was a lot of organization!  I re-used all my old files, and updated the post/put/delete routes to initiate the send as a callback.  My only question has to do with setting up the express server.  Now that we are parsing routes and models into different files, I'm not sure if I required everything in the right place.  Could you let me know if I used router, app, and mongo in all the right places?

Also, if I forgot any files, just give me a heads up...
Thanks!
-JB

### CODE REVIEW

**Comment by dabellator** [comment]
I just noticed your comment about route security for put, post and delete.  I'll do some research and try to update my assignment by Saturday, but do you have any resources about it?

Thanks!
-JB

**Comment by dabellator** [comment]
Looks like I keep coming up with questions...

Since tests and app are separate folders, should tests have it's own js/lib, or should mocha and chai just be placed inside of app/public/js/lib?  I know it's not a big deal, I just want to know what best practice usually is.
-JB

**Comment by jamdon** [comment]
For resources, I'm not sure what kind of resources you're looking for. For the tests, there's a couple of different ways you could go about it, but for the way I have the files currently organized, I would create separate folders inside the tests directory for testing the server-side app vs. the client-side app, and the client-side tests would maintain copies of the relevant files in that folder as opposed to using the node_modules directory for the testing of the server-side code. There's no "right" answer and there are a lot of different ways to organize files and directories.

**Comment by jamdon** [comment]
You're going to want, inside your public/js folder, a models, a collections, a views, and a templates directory for your project. Instead of assigning a 9th homework, I'll be giving the final project requirements and each directory will have some kind of implementation file in it for the final version of the project (still working on the details.)

**Comment by dabellator** [comment]
Thanks for pointing that out, I hadn't realized those directories weren't pushed up with my repo.  I have them on my local, so I assume they didn't push because they are empty.  I noticed in your project structure example that you include a readme in every directory.  Is that common practice?

For the resource question, I'm wondering if you could point me somewhere to read more about protecting put, post and delete routes.  Are you suggesting using some sort of tokens?  For the test best practices, I found some examples in the Mocha documentation.  I'll read through it, and if I have any questions I'll bug you about it at our next class!
-JB

**Comment by jamdon** [comment]
I wouldn't describe that as common practice, because generally people aren't creating empty folders in their projects. This repository has empty folders because it's part of the assignment, so the situation is a bit contrived. 

As far as your post/put/delete routes, what I'm getting at is that if you expose those routes, then anyone visiting your site could basically do whatever they wanted to with your data. The food truck data probably shouldn't be directly modifiable by the public. Even if you wanted to allow public users to add food trucks or modify existing ones, you'd still want to moderate that process. What I would recommend is cordoning off a part of your site as an "admin" area that is protected by authentication and only allowing modification of your data from there. Then, those routes would only support doing anything for an authenticated user (which would be tied into your authentication and could involve a token.) Until you have something like that set up, if you don't want your data messed with, I'd simply not expose the routes. We didn't have time to get into authentication, but this is the route I would recommend investigating if you're interested.

**Comment by dabellator** [comment]
Ah, ok, that makes sense.  I thought you were referring to CSRF and such...

I'll leave my empty folders as they are, but my repo is ready to go for the next assignment.
-JB

**Pull request closed without merging**
